FROM node:22.15-alpine

RUN apk update

WORKDIR /app/backend

EXPOSE 3000

COPY "package.json" "package-lock.json" ./

RUN npm i

COPY . .

RUN npx prisma generate

COPY prisma/generated .

CMD ["npm", "run", "start:dev"]

